// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/search/presentation/view_model/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/core/entities/product_entity.dart' as _i5;
import 'package:flowers_app/features/categories/data/models/request/get_products_params.dart'
    as _i6;
import 'package:flowers_app/features/search/domain/use_cases/clear_search_history_use_case.dart'
    as _i10;
import 'package:flowers_app/features/search/domain/use_cases/get_search_history_use_case.dart'
    as _i8;
import 'package:flowers_app/features/search/domain/use_cases/remove_search_query_use_case.dart'
    as _i11;
import 'package:flowers_app/features/search/domain/use_cases/save_search_query_use_case.dart'
    as _i9;
import 'package:flowers_app/features/search/domain/use_cases/search_products_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProductsUseCase extends _i1.Mock
    implements _i2.SearchProductsUseCase {
  MockSearchProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.ProductEntity>>> call(
    _i6.GetProductsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.ProductEntity>>>.value(
                  _i7.dummyValue<_i4.BaseResponse<List<_i5.ProductEntity>>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.ProductEntity>>>);
}

/// A class which mocks [GetSearchHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchHistoryUseCase extends _i1.Mock
    implements _i8.GetSearchHistoryUseCase {
  MockGetSearchHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}

/// A class which mocks [SaveSearchHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveSearchHistoryUseCase extends _i1.Mock
    implements _i9.SaveSearchHistoryUseCase {
  MockSaveSearchHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(List<String>? history) =>
      (super.noSuchMethod(
            Invocation.method(#call, [history]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ClearSearchHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearSearchHistoryUseCase extends _i1.Mock
    implements _i10.ClearSearchHistoryUseCase {
  MockClearSearchHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RemoveSearchQueryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveSearchQueryUseCase extends _i1.Mock
    implements _i11.RemoveSearchQueryUseCase {
  MockRemoveSearchQueryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(List<String>? history, String? query) =>
      (super.noSuchMethod(
            Invocation.method(#call, [history, query]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
