// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/auth/signup/data/repositories/signup_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/auth/signup/data/data_sources/signup_remote_data_source_contract.dart'
    as _i2;
import 'package:flowers_app/features/auth/signup/data/models/requestes/signup_request.dart'
    as _i6;
import 'package:flowers_app/features/auth/signup/data/models/responses/signup_response.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SignupRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRemoteDataSourceContract extends _i1.Mock
    implements _i2.SignupRemoteDataSourceContract {
  MockSignupRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.SignupResponse>> signup(
    _i6.SignupRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [request]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.SignupResponse>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.SignupResponse>>(
                this,
                Invocation.method(#signup, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.SignupResponse>>);
}
