// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/cart/data/repos/cart_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/cart/data/data_sources/cart_remote_data_source_contract.dart'
    as _i2;
import 'package:flowers_app/features/cart/data/models/response/cart_response.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRemoteDataSourceContract extends _i1.Mock
    implements _i2.CartRemoteDataSourceContract {
  MockCartRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartResponse>> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartResponse>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartResponse>>(
                this,
                Invocation.method(#getCart, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<String>> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i6.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#clearCart, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartResponse>> addToCart(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [productId, quantity]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartResponse>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartResponse>>(
                this,
                Invocation.method(#addToCart, [productId, quantity]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartResponse>> updateQuantity(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [productId, quantity]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartResponse>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartResponse>>(
                this,
                Invocation.method(#updateQuantity, [productId, quantity]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartResponse>> removeItem(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [productId]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartResponse>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartResponse>>(
                this,
                Invocation.method(#removeItem, [productId]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartResponse>>);
}
