// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/occasions/api/data_sources/occasions_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_app/features/occasions/api/api_client/occasions_api_client.dart'
    as _i4;
import 'package:flowers_app/features/occasions/data/models/responses/occasions_response.dart'
    as _i2;
import 'package:flowers_app/features/occasions/data/models/responses/products_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOccasionsResponse_0 extends _i1.SmartFake
    implements _i2.OccasionsResponse {
  _FakeOccasionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_1 extends _i1.SmartFake
    implements _i3.ProductsResponse {
  _FakeProductsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OccasionsApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccasionsApiClient extends _i1.Mock
    implements _i4.OccasionsApiClient {
  MockOccasionsApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.OccasionsResponse> getAllOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllOccasions, []),
            returnValue: _i5.Future<_i2.OccasionsResponse>.value(
              _FakeOccasionsResponse_0(
                this,
                Invocation.method(#getAllOccasions, []),
              ),
            ),
          )
          as _i5.Future<_i2.OccasionsResponse>);

  @override
  _i5.Future<_i3.ProductsResponse> getProductsByOccasion(
    String? occasionName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByOccasion, [occasionName]),
            returnValue: _i5.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProductsByOccasion, [occasionName]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductsResponse>);
}
