// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/address/data/repos/address_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/address/data/data_sources/address_local_data_source_contract.dart'
    as _i8;
import 'package:flowers_app/features/address/data/data_sources/address_remote_data_source_contract.dart'
    as _i2;
import 'package:flowers_app/features/address/data/models/address_model.dart'
    as _i7;
import 'package:flowers_app/features/address/data/models/address_response.dart'
    as _i5;
import 'package:flowers_app/features/address/data/models/city_model.dart'
    as _i10;
import 'package:flowers_app/features/address/data/models/governorate_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AddressRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRemoteDataSourceContract extends _i1.Mock
    implements _i2.AddressRemoteDataSourceContract {
  MockAddressRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.AddressResponse>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AddressResponse>>(
                    this,
                    Invocation.method(#getAddresses, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.AddressResponse>> addAddress(
    _i7.AddressModel? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [address]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AddressResponse>>(
                    this,
                    Invocation.method(#addAddress, [address]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.AddressResponse>> updateAddress(
    _i7.AddressModel? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [address]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AddressResponse>>(
                    this,
                    Invocation.method(#updateAddress, [address]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.AddressResponse>> deleteAddress(
    String? addressId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [addressId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AddressResponse>>(
                    this,
                    Invocation.method(#deleteAddress, [addressId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AddressResponse>>);
}

/// A class which mocks [AddressLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressLocalDataSourceContract extends _i1.Mock
    implements _i8.AddressLocalDataSourceContract {
  MockAddressLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i9.GovernorateModel>>> getGovernorates() =>
      (super.noSuchMethod(
            Invocation.method(#getGovernorates, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i9.GovernorateModel>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i9.GovernorateModel>>>(
                    this,
                    Invocation.method(#getGovernorates, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i9.GovernorateModel>>>);

  @override
  _i3.Future<_i4.BaseResponse<List<_i10.CityModel>>> getCities(
    String? governorateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCities, [governorateId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i10.CityModel>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i10.CityModel>>>(
                    this,
                    Invocation.method(#getCities, [governorateId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i10.CityModel>>>);
}
