// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/categories/domain/repositories/categories_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/categories/data/data_sources/categories_remote_data_source_impl.dart'
    as _i2;
import 'package:flowers_app/features/categories/data/models/request/get_products_params.dart'
    as _i8;
import 'package:flowers_app/features/categories/data/models/response/get_all_categories_response.dart'
    as _i5;
import 'package:flowers_app/features/categories/data/models/response/get_all_products_response.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CategoriesRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRemoteDataSourceImpl extends _i1.Mock
    implements _i2.CategoriesRemoteDataSourceImpl {
  MockCategoriesRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.GetAllCategoriesResponse>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<_i5.GetAllCategoriesResponse>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<_i5.GetAllCategoriesResponse>
                  >(this, Invocation.method(#getCategories, [])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.GetAllCategoriesResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i7.GetAllProductsResponse>> getProducts(
    _i8.GetProductsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [params]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i7.GetAllProductsResponse>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i7.GetAllProductsResponse>>(
                    this,
                    Invocation.method(#getProducts, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i7.GetAllProductsResponse>>);
}
