// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/checkout/presentation/view_model/checkout_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/checkout/data/models/checkout_requests/checkout_request.dart'
    as _i6;
import 'package:flowers_app/features/checkout/domain/entities/card_entity.dart'
    as _i9;
import 'package:flowers_app/features/checkout/domain/entities/order_entity.dart'
    as _i5;
import 'package:flowers_app/features/checkout/domain/use_cases/card_checkout_use_case.dart'
    as _i8;
import 'package:flowers_app/features/checkout/domain/use_cases/cash_checkout_use_case.dart'
    as _i2;
import 'package:flowers_app/features/checkout/domain/use_cases/get_delivery_dayes_use_case.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CashCheckoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashCheckoutUseCase extends _i1.Mock
    implements _i2.CashCheckoutUseCase {
  MockCashCheckoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.OrderEntity>> call(
    _i6.CheckoutRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.OrderEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.OrderEntity>>(
                this,
                Invocation.method(#call, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.OrderEntity>>);
}

/// A class which mocks [CardCheckoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardCheckoutUseCase extends _i1.Mock
    implements _i8.CardCheckoutUseCase {
  MockCardCheckoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i9.CardEntity>> call(
    String? cartId,
    _i6.CheckoutRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [cartId, request]),
            returnValue: _i3.Future<_i4.BaseResponse<_i9.CardEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i9.CardEntity>>(
                this,
                Invocation.method(#call, [cartId, request]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i9.CardEntity>>);
}

/// A class which mocks [GetDeliveryDaysUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDeliveryDaysUseCase extends _i1.Mock
    implements _i10.GetDeliveryDaysUseCase {
  MockGetDeliveryDaysUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() =>
      (super.noSuchMethod(Invocation.method(#call, []), returnValue: 0) as int);
}
