// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/cart/api/data_sources/cart_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_app/features/cart/api/api_client/cart_api_client.dart'
    as _i3;
import 'package:flowers_app/features/cart/data/models/request/add_to_cart_request.dart'
    as _i5;
import 'package:flowers_app/features/cart/data/models/request/update_quantity_request.dart'
    as _i6;
import 'package:flowers_app/features/cart/data/models/response/cart_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartResponse_0 extends _i1.SmartFake implements _i2.CartResponse {
  _FakeCartResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartApiClient extends _i1.Mock implements _i3.CartApiClient {
  MockCartApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i4.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i4.Future<_i2.CartResponse>);

  @override
  _i4.Future<_i2.CartResponse> addToCart(_i5.AddToCartRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [request]),
            returnValue: _i4.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#addToCart, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.CartResponse>);

  @override
  _i4.Future<_i2.CartResponse> updateQuantity(
    String? productId,
    _i6.UpdateQuantityRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [productId, request]),
            returnValue: _i4.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#updateQuantity, [productId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.CartResponse>);

  @override
  _i4.Future<_i2.CartResponse> removeItem(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [productId]),
            returnValue: _i4.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#removeItem, [productId]),
              ),
            ),
          )
          as _i4.Future<_i2.CartResponse>);

  @override
  _i4.Future<String> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#clearCart, [])),
            ),
          )
          as _i4.Future<String>);
}
