// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/address/presentation/view_model/address_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/address/domain/entities/address_entity.dart'
    as _i5;
import 'package:flowers_app/features/address/domain/entities/city_entity.dart'
    as _i13;
import 'package:flowers_app/features/address/domain/entities/governorate_entity.dart'
    as _i11;
import 'package:flowers_app/features/address/domain/use_cases/add_address_use_case.dart'
    as _i7;
import 'package:flowers_app/features/address/domain/use_cases/delete_address_use_case.dart'
    as _i9;
import 'package:flowers_app/features/address/domain/use_cases/get_addresses_use_case.dart'
    as _i2;
import 'package:flowers_app/features/address/domain/use_cases/get_cities_use_case.dart'
    as _i12;
import 'package:flowers_app/features/address/domain/use_cases/get_current_location_use_case.dart'
    as _i17;
import 'package:flowers_app/features/address/domain/use_cases/get_governorates_use_case.dart'
    as _i10;
import 'package:flowers_app/features/address/domain/use_cases/get_placemark_use_case.dart'
    as _i14;
import 'package:flowers_app/features/address/domain/use_cases/update_address_use_case.dart'
    as _i8;
import 'package:flowers_app/features/address/domain/utils/address_matcher.dart'
    as _i18;
import 'package:geocoding/geocoding.dart' as _i15;
import 'package:latlong2/latlong.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetAddressesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAddressesUseCase extends _i1.Mock
    implements _i2.GetAddressesUseCase {
  MockGetAddressesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.AddressEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>);
}

/// A class which mocks [AddAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddressUseCase extends _i1.Mock implements _i7.AddAddressUseCase {
  MockAddAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>> call(
    _i5.AddressEntity? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [address]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.AddressEntity>>>(
                    this,
                    Invocation.method(#call, [address]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>);
}

/// A class which mocks [UpdateAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAddressUseCase extends _i1.Mock
    implements _i8.UpdateAddressUseCase {
  MockUpdateAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>> call(
    _i5.AddressEntity? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [address]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.AddressEntity>>>(
                    this,
                    Invocation.method(#call, [address]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>);
}

/// A class which mocks [DeleteAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddressUseCase extends _i1.Mock
    implements _i9.DeleteAddressUseCase {
  MockDeleteAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>> call(
    String? addressId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [addressId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.AddressEntity>>>(
                    this,
                    Invocation.method(#call, [addressId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.AddressEntity>>>);
}

/// A class which mocks [GetGovernoratesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGovernoratesUseCase extends _i1.Mock
    implements _i10.GetGovernoratesUseCase {
  MockGetGovernoratesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i11.GovernorateEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<
                  _i4.BaseResponse<List<_i11.GovernorateEntity>>
                >.value(
                  _i6.dummyValue<
                    _i4.BaseResponse<List<_i11.GovernorateEntity>>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i11.GovernorateEntity>>>);
}

/// A class which mocks [GetCitiesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCitiesUseCase extends _i1.Mock implements _i12.GetCitiesUseCase {
  MockGetCitiesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i13.CityEntity>>> call(
    String? governorateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [governorateId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i13.CityEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i13.CityEntity>>>(
                    this,
                    Invocation.method(#call, [governorateId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i13.CityEntity>>>);
}

/// A class which mocks [GetPlacemarkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPlacemarkUseCase extends _i1.Mock
    implements _i14.GetPlacemarkUseCase {
  MockGetPlacemarkUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i15.Placemark?> call(_i16.LatLng? location) =>
      (super.noSuchMethod(
            Invocation.method(#call, [location]),
            returnValue: _i3.Future<_i15.Placemark?>.value(),
          )
          as _i3.Future<_i15.Placemark?>);
}

/// A class which mocks [GetCurrentLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentLocationUseCase extends _i1.Mock
    implements _i17.GetCurrentLocationUseCase {
  MockGetCurrentLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i16.LatLng?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i16.LatLng?>.value(),
          )
          as _i3.Future<_i16.LatLng?>);
}

/// A class which mocks [AddressMatcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressMatcher extends _i1.Mock implements _i18.AddressMatcher {
  MockAddressMatcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? matchGovernorate(
    List<_i11.GovernorateEntity>? governorates,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#matchGovernorate, [governorates, name]),
          )
          as String?);

  @override
  String? matchCity(List<_i13.CityEntity>? cities, _i15.Placemark? place) =>
      (super.noSuchMethod(Invocation.method(#matchCity, [cities, place]))
          as String?);

  @override
  String? matchCityByName(List<_i13.CityEntity>? cities, String? name) =>
      (super.noSuchMethod(Invocation.method(#matchCityByName, [cities, name]))
          as String?);
}
