// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/orders/presentation/view_model/orders_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/orders/domain/entities/order_entity.dart'
    as _i5;
import 'package:flowers_app/features/orders/domain/use_cases/get_active_orders_use_case.dart'
    as _i7;
import 'package:flowers_app/features/orders/domain/use_cases/get_completed_orders_use_case.dart'
    as _i8;
import 'package:flowers_app/features/orders/domain/use_cases/get_user_orders_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetUserOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserOrdersUseCase extends _i1.Mock
    implements _i2.GetUserOrdersUseCase {
  MockGetUserOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.OrderEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.OrderEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.OrderEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.OrderEntity>>>);
}

/// A class which mocks [GetActiveOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveOrdersUseCase extends _i1.Mock
    implements _i7.GetActiveOrdersUseCase {
  MockGetActiveOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.OrderEntity> call(List<_i5.OrderEntity>? orders) =>
      (super.noSuchMethod(
            Invocation.method(#call, [orders]),
            returnValue: <_i5.OrderEntity>[],
          )
          as List<_i5.OrderEntity>);
}

/// A class which mocks [GetCompletedOrdersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompletedOrdersUseCase extends _i1.Mock
    implements _i8.GetCompletedOrdersUseCase {
  MockGetCompletedOrdersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.OrderEntity> call(List<_i5.OrderEntity>? orders) =>
      (super.noSuchMethod(
            Invocation.method(#call, [orders]),
            returnValue: <_i5.OrderEntity>[],
          )
          as List<_i5.OrderEntity>);
}
