// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/best_seller/api/data_sources/best_seller_remote_data_sources_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_app/features/best_seller/api/api_client/best_seller_api_client.dart'
    as _i3;
import 'package:flowers_app/features/best_seller/data/models/best_seller_products_response/best_seller_products_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBestSellerProductsResponse_0 extends _i1.SmartFake
    implements _i2.BestSellerProductsResponse {
  _FakeBestSellerProductsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BestSellerApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBestSellerApiClient extends _i1.Mock
    implements _i3.BestSellerApiClient {
  MockBestSellerApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BestSellerProductsResponse> bestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#bestSeller, []),
            returnValue: _i4.Future<_i2.BestSellerProductsResponse>.value(
              _FakeBestSellerProductsResponse_0(
                this,
                Invocation.method(#bestSeller, []),
              ),
            ),
          )
          as _i4.Future<_i2.BestSellerProductsResponse>);
}
