// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/search/data/repos/search_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/categories/data/models/request/get_products_params.dart'
    as _i6;
import 'package:flowers_app/features/categories/data/models/response/get_all_products_response.dart'
    as _i5;
import 'package:flowers_app/features/search/data/data_sources/search_local_data_source.dart'
    as _i8;
import 'package:flowers_app/features/search/data/data_sources/search_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRemoteDataSource extends _i1.Mock
    implements _i2.SearchRemoteDataSource {
  MockSearchRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.GetAllProductsResponse>> searchProducts(
    _i6.GetProductsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [params]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.GetAllProductsResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.GetAllProductsResponse>>(
                    this,
                    Invocation.method(#searchProducts, [params]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.GetAllProductsResponse>>);
}

/// A class which mocks [SearchLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchLocalDataSource extends _i1.Mock
    implements _i8.SearchLocalDataSource {
  MockSearchLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> getSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getSearchHistory, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> saveSearchHistory(List<String>? history) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearchHistory, [history]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearSearchHistory, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
