// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/auth/forgot-password/presentation/view_model/cubit/forgot_password_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/auth/forgot-password/domain/entites/forget_password_entity.dart'
    as _i5;
import 'package:flowers_app/features/auth/forgot-password/domain/forgot_password_use_cases/forgot_password_use_case.dart'
    as _i2;
import 'package:flowers_app/features/auth/forgot-password/domain/forgot_password_use_cases/reset_password_use_case.dart'
    as _i8;
import 'package:flowers_app/features/auth/forgot-password/domain/forgot_password_use_cases/verify_reset_code_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgotPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordUseCase extends _i1.Mock
    implements _i2.ForgotPasswordUseCase {
  MockForgotPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>> call({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ForgotPasswordEntity>>(
                    this,
                    Invocation.method(#call, [], {#email: email}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>);
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i7.VerifyResetCodeUseCase {
  MockVerifyResetCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>> call({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#resetCode: resetCode}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ForgotPasswordEntity>>(
                    this,
                    Invocation.method(#call, [], {#resetCode: resetCode}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i8.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>> call({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.ForgotPasswordEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #email: email,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordEntity>>);
}
