// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/auth/forgot-password/data/repo/forgot_password_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/auth/forgot-password/api/data_sources/forgot_password_remote_data_source_impl.dart'
    as _i2;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/forgot_password_request.dart'
    as _i6;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/reset_password_request.dart'
    as _i11;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/verify_reset_code_request.dart'
    as _i9;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/forgot_password_response.dart'
    as _i5;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/reset_password_response.dart'
    as _i10;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/verify_reset_code_response.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgotPasswordRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordRemoteDataSourceImpl extends _i1.Mock
    implements _i2.ForgotPasswordRemoteDataSourceImpl {
  MockForgotPasswordRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordResponse>> forgotPassword(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.ForgotPasswordResponse>>(
                    this,
                    Invocation.method(#forgotPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgotPasswordResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.VerifyResetCodeResponse>> verifyResetCode(
    _i9.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.VerifyResetCodeResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i8.VerifyResetCodeResponse>>(
                    this,
                    Invocation.method(#verifyResetCode, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.VerifyResetCodeResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>> resetPassword(
    _i11.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i10.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>>);
}
