// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeinskTqpleG2wl0OHCnCTpMyZR4sVCt0',
    appId: '1:95850025186:web:cfb65a751c6ac48d804ebb',
    messagingSenderId: '95850025186',
    projectId: 'flowers-app-f2600',
    authDomain: 'flowers-app-f2600.firebaseapp.com',
    storageBucket: 'flowers-app-f2600.firebasestorage.app',
    measurementId: 'G-6LPKSFCL3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTFBbSeuJ5GAKMadrWheZGHm-O25CZOE',
    appId: '1:95850025186:android:1c41bd44a9ac37a7804ebb',
    messagingSenderId: '95850025186',
    projectId: 'flowers-app-f2600',
    storageBucket: 'flowers-app-f2600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jz3IZ8BJCruUso8VagmcQvH79UQfCQs',
    appId: '1:95850025186:ios:9ab69172805a2f4f804ebb',
    messagingSenderId: '95850025186',
    projectId: 'flowers-app-f2600',
    storageBucket: 'flowers-app-f2600.firebasestorage.app',
    iosBundleId: 'com.example.flowersApp',
  );

}