// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/categories/data/data_sources/categories_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_app/features/categories/api/api_client/categories_api_client.dart'
    as _i4;
import 'package:flowers_app/features/categories/data/models/response/get_all_categories_response.dart'
    as _i2;
import 'package:flowers_app/features/categories/data/models/response/get_all_products_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAllCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.GetAllCategoriesResponse {
  _FakeGetAllCategoriesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllProductsResponse_1 extends _i1.SmartFake
    implements _i3.GetAllProductsResponse {
  _FakeGetAllProductsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoriesApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesApiClient extends _i1.Mock
    implements _i4.CategoriesApiClient {
  MockCategoriesApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GetAllCategoriesResponse> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<_i2.GetAllCategoriesResponse>.value(
              _FakeGetAllCategoriesResponse_0(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i5.Future<_i2.GetAllCategoriesResponse>);

  @override
  _i5.Future<_i3.GetAllProductsResponse> getProducts({
    Map<String, dynamic>? queries,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#queries: queries}),
            returnValue: _i5.Future<_i3.GetAllProductsResponse>.value(
              _FakeGetAllProductsResponse_1(
                this,
                Invocation.method(#getProducts, [], {#queries: queries}),
              ),
            ),
          )
          as _i5.Future<_i3.GetAllProductsResponse>);
}
