// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/profile/edit_profile/presentation/view_model/edit_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i9;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/profile/edit_profile/data/models/edit_profile_request/edit_profile_request.dart'
    as _i6;
import 'package:flowers_app/features/profile/edit_profile/domain/entities/user_edit_profile_entity.dart'
    as _i5;
import 'package:flowers_app/features/profile/edit_profile/domain/use_cases/edit_profile_use_case.dart'
    as _i2;
import 'package:flowers_app/features/profile/edit_profile/domain/use_cases/upload_photo_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i2.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UserEditProfileEntity>> call(
    _i6.EditProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.UserEditProfileEntity>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.UserEditProfileEntity>>(
                    this,
                    Invocation.method(#call, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UserEditProfileEntity>>);
}

/// A class which mocks [UploadProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfileUseCase extends _i1.Mock
    implements _i8.UploadProfileUseCase {
  MockUploadProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<String>> call(_i9.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#call, [file]),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i7.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#call, [file]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);
}
