// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/profile/reset_password/presentation/view_model/change_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/config/cache/secure_cache_helper.dart' as _i6;
import 'package:flowers_app/features/profile/reset_password/domain/use_cases/change_password_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChangePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChangePasswordUseCase extends _i1.Mock
    implements _i2.ChangePasswordUseCase {
  MockChangePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<String>> call(
    String? password,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [password, newPassword]),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i5.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#call, [password, newPassword]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);
}

/// A class which mocks [SecureCacheHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureCacheHelper extends _i1.Mock implements _i6.SecureCacheHelper {
  MockSecureCacheHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> writeData({required String? key, required dynamic value}) =>
      (super.noSuchMethod(
            Invocation.method(#writeData, [], {#key: key, #value: value}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> readData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#readData, [], {#key: key}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> containsKey({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {#key: key}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteData({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteData, [], {#key: key}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
