// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/home/presentation/view_model/cubit/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/core/enities/product_entity.dart' as _i10;
import 'package:flowers_app/features/best_seller/domain/use_cases/best_seller_use_case.dart'
    as _i9;
import 'package:flowers_app/features/categories/domain/entities/category_entity.dart'
    as _i8;
import 'package:flowers_app/features/categories/domain/use_cases/get_categories_use_case.dart'
    as _i7;
import 'package:flowers_app/features/occasions/domain/entities/occasion_entity.dart'
    as _i5;
import 'package:flowers_app/features/occasions/domain/use_cases/occasions_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OccasionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccasionsUseCase extends _i1.Mock implements _i2.OccasionsUseCase {
  MockOccasionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.OccasionEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.OccasionEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.OccasionEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.OccasionEntity>>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i7.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i8.CategoriesEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.CategoriesEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i8.CategoriesEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.CategoriesEntity>>);
}

/// A class which mocks [BestSellerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBestSellerUseCase extends _i1.Mock implements _i9.BestSellerUseCase {
  MockBestSellerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i10.ProductEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i10.ProductEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i10.ProductEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i10.ProductEntity>>>);
}
