// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/cart/presentation/view_model/cart_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/base_response.dart' as _i4;
import 'package:flowers_app/features/cart/domain/entities/cart_entity.dart'
    as _i5;
import 'package:flowers_app/features/cart/domain/use_cases/add_to_cart_use_case.dart'
    as _i7;
import 'package:flowers_app/features/cart/domain/use_cases/clear_cart_use_case.dart'
    as _i10;
import 'package:flowers_app/features/cart/domain/use_cases/get_cart_use_case.dart'
    as _i2;
import 'package:flowers_app/features/cart/domain/use_cases/remove_item_use_case.dart'
    as _i9;
import 'package:flowers_app/features/cart/domain/use_cases/update_quantity_use_case.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCartUseCase extends _i1.Mock implements _i2.GetCartUseCase {
  MockGetCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartEntity>>);
}

/// A class which mocks [AddToCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddToCartUseCase extends _i1.Mock implements _i7.AddToCartUseCase {
  MockAddToCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartEntity>> call(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productId, quantity]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartEntity>>(
                this,
                Invocation.method(#call, [productId, quantity]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartEntity>>);
}

/// A class which mocks [UpdateQuantityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateQuantityUseCase extends _i1.Mock
    implements _i8.UpdateQuantityUseCase {
  MockUpdateQuantityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartEntity>> call(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productId, quantity]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartEntity>>(
                this,
                Invocation.method(#call, [productId, quantity]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartEntity>>);
}

/// A class which mocks [RemoveItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveItemUseCase extends _i1.Mock implements _i9.RemoveItemUseCase {
  MockRemoveItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.CartEntity>> call(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [productId]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.CartEntity>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.CartEntity>>(
                this,
                Invocation.method(#call, [productId]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.CartEntity>>);
}

/// A class which mocks [ClearCartUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCartUseCase extends _i1.Mock implements _i10.ClearCartUseCase {
  MockClearCartUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i6.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);
}
