// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/auth/forgot-password/api/data_sources/forgot_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flowers_app/features/auth/forgot-password/api/api_client/forgot_password_api_client.dart'
    as _i5;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/forgot_password_request.dart'
    as _i7;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/reset_password_request.dart'
    as _i9;
import 'package:flowers_app/features/auth/forgot-password/data/models/request/verify_reset_code_request.dart'
    as _i8;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/forgot_password_response.dart'
    as _i2;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/reset_password_response.dart'
    as _i4;
import 'package:flowers_app/features/auth/forgot-password/data/models/response/verify_reset_code_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgotPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgotPasswordResponse {
  _FakeForgotPasswordResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponse_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponse {
  _FakeVerifyResetCodeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponse {
  _FakeResetPasswordResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgotPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordApiClient extends _i1.Mock
    implements _i5.ForgotPasswordApiClient {
  MockForgotPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ForgotPasswordResponse> forgotPassword(
    _i7.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i6.Future<_i2.ForgotPasswordResponse>.value(
              _FakeForgotPasswordResponse_0(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.ForgotPasswordResponse>);

  @override
  _i6.Future<_i3.VerifyResetCodeResponse> verifyResetCode(
    _i8.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue: _i6.Future<_i3.VerifyResetCodeResponse>.value(
              _FakeVerifyResetCodeResponse_1(
                this,
                Invocation.method(#verifyResetCode, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.VerifyResetCodeResponse>);

  @override
  _i6.Future<_i4.ResetPasswordResponse> resetPassword(
    _i9.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i6.Future<_i4.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_2(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.ResetPasswordResponse>);
}
