// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/checkout/api/data_sourses/checkout_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_app/config/services/remote_config_service.dart' as _i7;
import 'package:flowers_app/features/checkout/api/checkout_api_client/checkout_api_client.dart'
    as _i4;
import 'package:flowers_app/features/checkout/data/models/checkout_requests/checkout_request.dart'
    as _i6;
import 'package:flowers_app/features/checkout/data/models/checkout_responses/card_response/card_checkout_response.dart'
    as _i3;
import 'package:flowers_app/features/checkout/data/models/checkout_responses/cash_response/cash_checkout_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCashCheckoutResponse_0 extends _i1.SmartFake
    implements _i2.CashCheckoutResponse {
  _FakeCashCheckoutResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCardCheckoutResponse_1 extends _i1.SmartFake
    implements _i3.CardCheckoutResponse {
  _FakeCardCheckoutResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckoutApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckoutApiClient extends _i1.Mock implements _i4.CheckoutApiClient {
  MockCheckoutApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CashCheckoutResponse> cashCheckout(
    _i6.CheckoutRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cashCheckout, [request]),
            returnValue: _i5.Future<_i2.CashCheckoutResponse>.value(
              _FakeCashCheckoutResponse_0(
                this,
                Invocation.method(#cashCheckout, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.CashCheckoutResponse>);

  @override
  _i5.Future<_i3.CardCheckoutResponse> cardCheckout(
    String? url,
    _i6.CheckoutRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cardCheckout, [url, request]),
            returnValue: _i5.Future<_i3.CardCheckoutResponse>.value(
              _FakeCardCheckoutResponse_1(
                this,
                Invocation.method(#cardCheckout, [url, request]),
              ),
            ),
          )
          as _i5.Future<_i3.CardCheckoutResponse>);
}

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i7.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get deliveryDays =>
      (super.noSuchMethod(Invocation.getter(#deliveryDays), returnValue: 0)
          as int);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
