// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/profile/edit_profile/api/data_sources/edit_profile_remote_data_sourct_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i7;
import 'package:flowers_app/features/profile/edit_profile/api/api_client/edit_profile_api_client.dart'
    as _i4;
import 'package:flowers_app/features/profile/edit_profile/data/models/edit_profile_request/edit_profile_request.dart'
    as _i6;
import 'package:flowers_app/features/profile/edit_profile/data/models/edit_profile_response/edit_profile_response.dart'
    as _i2;
import 'package:flowers_app/features/profile/edit_profile/data/models/edit_profile_response/upload_photo_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEditProfileResponse_0 extends _i1.SmartFake
    implements _i2.EditProfileResponse {
  _FakeEditProfileResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadPhotoResponse_1 extends _i1.SmartFake
    implements _i3.UploadPhotoResponse {
  _FakeUploadPhotoResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileApiClient extends _i1.Mock
    implements _i4.EditProfileApiClient {
  MockEditProfileApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.EditProfileResponse> editProfile(
    _i6.EditProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i5.Future<_i2.EditProfileResponse>.value(
              _FakeEditProfileResponse_0(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.EditProfileResponse>);

  @override
  _i5.Future<_i3.UploadPhotoResponse> uploadPhoto(_i7.MultipartFile? image) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [image]),
            returnValue: _i5.Future<_i3.UploadPhotoResponse>.value(
              _FakeUploadPhotoResponse_1(
                this,
                Invocation.method(#uploadPhoto, [image]),
              ),
            ),
          )
          as _i5.Future<_i3.UploadPhotoResponse>);
}
