// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/search/data/data_sources/search_local_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/cache/hive_helper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HiveHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveHelper extends _i1.Mock implements _i2.HiveHelper {
  MockHiveHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheData<T>({
    required String? boxName,
    required String? key,
    required T? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheData, [], {
              #boxName: boxName,
              #key: key,
              #value: value,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<T?> getData<T>({required String? boxName, required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#boxName: boxName, #key: key}),
            returnValue: _i3.Future<T?>.value(),
          )
          as _i3.Future<T?>);

  @override
  _i3.Future<void> deleteData({
    required String? boxName,
    required String? key,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteData, [], {#boxName: boxName, #key: key}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearBox({required String? boxName}) =>
      (super.noSuchMethod(
            Invocation.method(#clearBox, [], {#boxName: boxName}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
