// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/address/api/data_sources/address_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_app/features/address/api/api_client/address_api_client.dart'
    as _i3;
import 'package:flowers_app/features/address/data/models/address_model.dart'
    as _i5;
import 'package:flowers_app/features/address/data/models/address_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAddressResponse_0 extends _i1.SmartFake
    implements _i2.AddressResponse {
  _FakeAddressResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddressApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressApiClient extends _i1.Mock implements _i3.AddressApiClient {
  MockAddressApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AddressResponse> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#getAddresses, []),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);

  @override
  _i4.Future<_i2.AddressResponse> addAddress(_i5.AddressModel? address) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [address]),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#addAddress, [address]),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);

  @override
  _i4.Future<_i2.AddressResponse> updateAddress(
    String? id,
    _i5.AddressModel? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [id, address]),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#updateAddress, [id, address]),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);

  @override
  _i4.Future<_i2.AddressResponse> deleteAddress(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#deleteAddress, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);
}
