name: Android Development Build

on:
  push:
    branches:
      - develop
      - release/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.7

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Create Firebase Credentials File
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase.json

      - name: Run Fastlane
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_SERVICE_ACCOUNT_PATH: ../firebase.json
        run: fastlane dev
